# Generated by Django 4.2.5 on 2023-10-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtoshort',
            name='desktop_visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='longtoshort',
            name='mobile_visits',
            field=models.IntegerField(default=0),
        ),
    ]
